# Generated by Django 5.2 on 2025-04-11 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_image_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='section',
            field=models.CharField(choices=[('regional', 'Regional'), ('national', 'National'), ('editorial', 'Editorial'), ('provincial', 'Provincial'), ('legal', 'Legal')], max_length=20),
        ),
    ]
